spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:~/testdb  # 인메모리 H2 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화
      path: /h2-console
  sql:
    init:
      mode: always

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

